import Head from "next/head";
import FileSaver from "file-saver";
import { SocialIcon } from "react-social-icons";
import Terminal from "react-animated-term";
import 'react-animated-term/dist/react-animated-term.css'

import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
  AiFillMail,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import dev from "../public/profilepic.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const saveFile = () => {
    FileSaver.saveAs(
      "/FinalResume1.pdf",
      "MyCV.pdf"
    );
  };

  const termLines = [
    {
      'text': 'ls Me/Skills',
      'cmd': true,
    },
    {
      'text': '.cpp    .cs   .java   .js   .py   .html   .css   .sql  .c  .cmd .mm .php',
      'cmd': false,
    },
    {
      'text': '',
      'cmd': true
    }
  ]

  const experienceLines = [
    {
      'text': 'cd Experience',
      'cmd': true,
    },
    {
      'text': 'cd KoolHaus',
      'cmd': true,
    },
    {
      'text': 'ls Stack_Used',
      'cmd': true
    },
    {
      'text': '.cs .unity .mm',
      'cmd': false
    },
    {
      'text': 'cd .. ',
      'cmd': true
    },
    {
      'text': 'ls TechnicalSkills',
      'cmd': true
    },
    {
      'text': 'XCode  Unity  Perforce',
      'cmd': false
    },
    {
      'text': '',
      'cmd': true
    }
  ]

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="font-burtons text-xl dark:text-gray-300">
              Hey There!
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="dark:text-gray-400"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                  onClick={saveFile}
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl max-w-lg mx-auto">
              Shubham Malhotra
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Software Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-80 md:text-xl dark:text-white">
              Welcome to my personal website! Here, you can find out more about
              my experience as a software developer and the projects I have
              worked on.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-200 hover:opacity-100 transition duration-300 ease-in-out">
              <a href="malhot91@uwindsor.ca">
              <AiFillMail className="hover:scale-110 transition duration-300 ease-in-out"/>
              </a>
              <a href="https://www.linkedin.com/in/shubham-malhotra-0a915222b/" >
              <AiFillLinkedin className="hover:scale-110 transition duration-300 ease-in-out"/>
              </a>
              <a href="https://github.com/QTMushy">
              <AiFillGithub className="hover:scale-110 transition duration-300 ease-in-out"/>
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={dev} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">
              Programming Languages
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Welcome to my Programming Languages section! I am a software
              engineer with a passion for coding and a wide range of programming
              language knowledge. Here, you'll find a list of the languages I
              know and brief descriptions of each.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="shadow-lg p-10 rounded-xl my-10 dark:bg-gray-900 flex-1">
              {/* <Image src={code} width={100} height={100} />
              <h2 className="py-4 text-gray-800 text-2xl dark:text-gray-300">
                C
              </h2>
              <h2 className="py-4 text-gray-800 text-2xl dark:text-gray-300">
                C++
              </h2>
              <h2 className="py-4 text-gray-800 text-2xl dark:text-gray-300">
                Java
              </h2>
              <h2 className="py-4 text-gray-800 text-2xl dark:text-gray-300">
                Python
              </h2>
              <h2 className="py-4 text-gray-800 text-2xl dark:text-gray-300">
                HTML
              </h2>
              <h2 className="py-4 text-gray-800 text-2xl dark:text-gray-300">
                CSS
              </h2>
              <h2 className="py-4 text-gray-800 text-2xl dark:text-gray-300">
                JavaScript
              </h2>
              <h2 className="py-4 text-gray-800 text-2xl dark:text-gray-300">
                C#
              </h2>
              <h2 className="py-4 text-gray-800 text-2xl dark:text-gray-300">
                React
              </h2>
              <h2 className="py-4 text-gray-800 text-2xl dark:text-gray-300">
                Objective C
              </h2> */}
               <Terminal lines={termLines} interval={200} className=" text-2xl" white/>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-4xl py-1 dark:text-white">Job Experience</h3>
            <h3 className="text-2xl py-2 text-teal-600 font-medium md:text-6xl max-w-lg mx-auto">
              KoolHaus Games
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              As a Software Engineer at the game studio, I had the opportunity
              to work on the development an upcoming mobile game
              set to launch in the near future. I was part of a team of
              developers who worked together to create a fun and engaging game
              experience for players. My role in the development process was to
              design and implement game features and mechanics. This involved a
              lot of coding and debugging, as well as collaborating with other
              team members to troubleshoot issues and maintain a high level of
              quality throughout the development process. Additionally, I was
              also responsible for testing the game and ensuring that it met the
              studio's standards. I am proud to have been a part of the
              development of an upcomming mobile game, and I am looking forward to its
              release. I am confident that the game will be a success and that
              players will enjoy it.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="shadow-lg p-10 rounded-xl my-10  dark:bg-gray-900 flex-1 text-5xl">
              {/* <h2 className="py-4 text-gray-800 text-2xl dark:text-gray-300">
                Stack Used
              </h2>
              <h2 className="py-4 text-gray-800 text-2xl dark:text-gray-300">
                C#
              </h2>
              <h2 className="py-4 text-gray-800 text-2xl dark:text-gray-300">
                Unity
              </h2>
              <h2 className="py-4 text-gray-800 text-2xl dark:text-gray-300">
                Objective C
              </h2>
              <h2 className="py-4 text-gray-800 text-2xl dark:text-gray-300">
                Perforce
              </h2>
              <h2 className="py-4 text-gray-800 text-2xl dark:text-gray-300">
                XCode
              </h2>
            </div> */}
            <Terminal lines={experienceLines} delay={300} white/>
            </div>
          </div>
          <h3 className="text-2xl py-2 text-teal-600 font-medium md:text-6xl max-w-lg mx-auto">
            Teaching Assistant
          </h3>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            I am serving as a Teaching Assistant for the Data Structures and
            Algorithms course at University of Windsor. In this role, I
            have been responsible for teaching lab sections of up to 25
            students, providing assistance and guidance to students, and helping
            to facilitate course material. I have also graded assignments, held
            office hours to answer student questions, and held review sessions
            prior to exams. My experience as a Teaching Assistant has enabled me
            to develop my skills in communication, problem-solving, and
            time-management. My experience has also given me a stronger
            understanding of the Data Structures and Algorithms course material,
            as well as the ability to explain difficult concepts in clear and
            concise terms. I have also gained valuable knowledge in the field of
            teaching and learning through my experience as a Teaching Assistant.
          </p>
        </section>
      </main>
    </div>
  );
}
